global:
  resolve_timeout: 1m

route:
  receiver: telegram
  group_by: ["alertname", "device_name", "ip"]
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 2h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "8534000885:AAFC0LscQaHT53ebKibUGmbq0cNDW6Gr7Po"
        chat_id: 1068617352
        parse_mode: "HTML"
        message: |
          ðŸš¨ <b>{{ .Status | toUpper }}</b> â€” <b>{{ .CommonLabels.alertname }}</b>
          <b>Device:</b> {{ .CommonLabels.device_name }}
          <b>IP:</b> {{ .CommonLabels.ip }}
          <b>Summary:</b> {{ .CommonAnnotations.summary }}
